version: '3'
services:
  postgres:
    image: postgres
    container_name: userRegister
    environment:

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
